import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_componants/navbar/navbar";
import Footer from "./_componants/footer/footer";
import { Toaster } from "react-hot-toast";
import NextauthProvaider from "./provaider/nextauthprovaider";
import Providers from "./provaider/react-qwery-provaider";
import Breadcrumbs from "./_componants/Breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bacground-home `}
      >
        <Providers>
          <NextauthProvaider>
            <Toaster />
            <Navbar />
            <Breadcrumbs />
            <div className="container mx-auto max-w-7xl">{children}</div>

            <Footer />
          </NextauthProvaider>
        </Providers>
      </body>
    </html>
  );
}
